{{ if .Values.plgx.rsyslogf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polylogyx.fullname" . }}-rsyslogf
  {{ if .Values.plgx.rsyslogf.annotations }}
  annotations: {{ .Values.plgx.rsyslogf.annotations | nindent 4 }}
  {{ end }}
  labels:
    name: {{ template "polylogyx.fullname" . }}-rsyslogf
spec:
  replicas: {{ .Values.plgx.rsyslogf.replicas }}
  selector:
    matchLabels:
      name: {{ template "polylogyx.fullname" . }}-rsyslogf
  template:
    metadata:
      {{ if .Values.plgx.rsyslogf.annotations }}
      annotations: {{ .Values.plgx.rsyslogf.annotations | nindent 4 }}
      {{ end }}
      labels:
        name: {{ template "polylogyx.fullname" . }}-rsyslogf
    spec:
      containers:
      - name: {{ template "polylogyx.fullname" . }}-rsyslogf
        image: {{ .Values.plgx.rsyslogf.image }}
        imagePullPolicy: {{ .Values.plgx.rsyslogf.pullPolicy | quote }}
        resources: {{ toYaml .Values.plgx.rsyslogf.resources | nindent 12 }}
        ports:
        - containerPort: 514
          name: tcp
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "polylogyx.fullname" . }}-rsyslogf-cfg
      - name: log-volume
        {{- if .Values.plgx.rsyslogf.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "polylogyx.rsyslogf.pvcName" . }}
        {{- else }}
        emptyDir: {}
        {{ end }}
      restartPolicy: Always
      {{ if .Values.plgx.rsyslogf.nodeSelector }}
      nodeSelector: {{ toYaml .Values.plgx.rsyslogf.nodeSelector | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.rsyslogf.tolerations }}
      tolerations: {{ toYaml .Values.plgx.rsyslogf.tolerations | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.rsyslogf.affinity }}
      affinity: {{ toYaml .Values.plgx.rsyslogf.affinity | nindent 8 }}
      {{ end }}
{{ end }}