{{- if and .Values.plgx.rsyslogf.persistence.enabled (not .Values.plgx.rsyslogf.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "polylogyx.fullname" . }}-rsyslogf-pvc
  labels:
    name: {{ template "polylogyx.fullname" . }}-rsyslogf-pvc
spec:
  accessModes:
    - {{ .Values.plgx.rsyslogf.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.plgx.rsyslogf.persistence.size | quote }}
  {{- include "polylogyx.rsyslogf.storageClass" . | nindent 2 }}
{{- end -}}