{{ if .Values.plgx.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polylogyx.fullname" . }}-esp-ui
  labels:
    name: {{ template "polylogyx.fullname" . }}-esp-ui
  {{ if .Values.plgx.ui.annotations }}
  annotations: {{ .Values.plgx.ui.annotations | nindent 4 }}
  {{ end }}
spec:
  replicas: {{ .Values.plgx.ui.replicas }}
  selector:
    matchLabels:
      name: {{ template "polylogyx.fullname" . }}-esp-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ template "polylogyx.fullname" . }}-esp-ui
      {{ if .Values.plgx.ui.annotations }}
      annotations: {{ .Values.plgx.ui.annotations | nindent 8 }}
      {{ end }}
    spec:
      containers:
        - name: {{ template "polylogyx.fullname" . }}-esp-ui
          image: {{ .Values.plgx.ui.image }}
          imagePullPolicy: {{ .Values.plgx.ui.pullPolicy | quote }}
          ports:
            - containerPort: 5000
          resources: {{ toYaml .Values.plgx.ui.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /src/plgx-esp-ui/carves
              name: carves
            - mountPath: /src/plgx-esp-ui/yara
              name: yara
          envFrom:
            - secretRef:
                name: {{ template "polylogyx.fullname" . }}-env-secret
      restartPolicy: Always
      {{ if .Values.plgx.ui.nodeSelector }}
      nodeSelector: {{ toYaml .Values.plgx.ui.nodeSelector | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.ui.tolerations }}
      tolerations: {{ toYaml .Values.plgx.ui.tolerations | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.ui.affinity }}
      affinity: {{ toYaml .Values.plgx.ui.affinity | nindent 8 }}
      {{ end }}
      volumes:
        - name: carves
          {{ if .Values.plgx.persistence.carves.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "polylogyx.carves.pvcName" . }}
          {{ else }}
            emptyDir: {}
          {{ end }}
        - name: yara
          {{ if .Values.plgx.persistence.yara.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "polylogyx.yara.pvcName" . }}
          {{ else }}
            emptyDir: {}
          {{ end }}
{{ end }}