{{ if .Values.plgx.esp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polylogyx.fullname" . }}-esp
  annotations: null
  labels:
    name: {{ template "polylogyx.fullname" . }}-esp
spec:
  replicas: {{ .Values.plgx.esp.replicas }}
  selector:
    matchLabels:
      name: {{ template "polylogyx.fullname" . }}-esp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ template "polylogyx.fullname" . }}-esp
      {{ if .Values.plgx.esp.annotations }}
      annotations: {{ toYaml .Values.plgx.esp.annotations | nindent 8 }}
      {{ end }}
    spec:
      containers:
        - name: {{ template "polylogyx.fullname" . }}-esp
          image: {{ .Values.plgx.esp.image }}
          imagePullPolicy: {{ .Values.plgx.esp.pullPolicy | quote }}
          resources: {{ toYaml .Values.plgx.esp.resources | nindent 12 }}
          ports:
            - containerPort: 6000
            - containerPort: 5555
          envFrom:
            - secretRef:
                name: {{ template "polylogyx.fullname" . }}-env-secret
          volumeMounts:
            - mountPath: /src/plgx-esp/carves
              name: carves
      restartPolicy: Always
      {{ if .Values.plgx.esp.nodeSelector }}
      nodeSelector: {{ toYaml .Values.plgx.esp.nodeSelector | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.esp.tolerations }}
      tolerations: {{ toYaml .Values.plgx.esp.tolerations | nindent 8 }}
      {{ end }}
      {{ if .Values.plgx.esp.affinity }}
      affinity: {{ toYaml .Values.plgx.esp.affinity | nindent 8 }}
      {{ end }}
      volumes:
        - name: carves
          {{ if .Values.plgx.persistence.carves.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "polylogyx.carves.pvcName" . }}
          {{ else }}
            emptyDir: {}
          {{ end }}
{{ end }}