{{ if .Values.plgx.esp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polylogyx.fullname" . }}-esp
  {{ if .Values.plgx.esp.annotations }}
  annotations: {{ .Values.plgx.esp.annotations | nindent 4 }}
  {{ end }}
  labels:
    name: {{ template "polylogyx.fullname" . }}-esp
spec:
  type: {{ .Values.plgx.esp.service.type }}
  {{- if eq .Values.plgx.esp.service.type "LoadBalancer" }}
  {{- if .Values.plgx.esp.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.plgx.esp.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  {{- if (or (eq .Values.plgx.esp.service.type "LoadBalancer") (eq .Values.plgx.esp.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.plgx.esp.service.externalTrafficPolicy | quote }}
  {{- end }}
  selector:
    name: {{ template "polylogyx.fullname" . }}-esp
  ports:
    - name: "6000"
      port: 6000
      targetPort: 6000
    - name: "5555"
      port: 5555
      targetPort: 5555
{{ end }}