apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polylogyx.fullname" . }}-esp-fileserver-configmap
data:
  osquery.flags: |
    --disable_events=false
    --allow_unsafe
    --audit_allow_config=true
    --audit_allow_process_events=true
    --audit_allow_sockets
    --audit_persist=true
    --disable_audit=false
    --events_expiry=3600
    --events_max=2500
    --pidfile=/private/var/osquery/osquery.pid
    --host_identifier=uuid
    --database_path=/private/var/osquery/osquery.db
    --config_plugin=tls
    --config_tls_endpoint=/esp/config
    --config_tls_refresh=300
    --config_tls_max_attempts=5
    --enroll_tls_endpoint=/esp/enroll
    --enroll_secret_path=/private/var/osquery/secret.txt
    --disable_distributed=false
    --distributed_plugin=tls
    --distributed_interval=15
    --distributed_tls_max_attempts=5
    --distributed_tls_read_endpoint=/esp/distributed/read
    --distributed_tls_write_endpoint=/esp/distributed/write
    --logger_plugin=tls
    --logger_tls_endpoint=/esp/log
    --logger_tls_period=30
    {{- if .Values.plgx.ingress.enabled }}
    --tls_hostname={{ .Values.plgx.ingress.host }}
    {{- end }}
    --log_result_events=false
    --pack_delimiter=/
    --disable_carver=false
    --carver_block_size=300000
    --carver_start_endpoint=/esp/start_uploads
    --carver_continue_endpoint=/esp/upload_blocks
    --carver_disable_function=false
    --watchdog_level=-1
    --utc