{{ if .Values.plgx.fileserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polylogyx.fullname" . }}-fileserver
  labels:
    name: {{ template "polylogyx.fullname" . }}-fileserver
spec:
  type: {{ .Values.plgx.fileserver.service.type }}
  {{- if eq .Values.plgx.fileserver.service.type "LoadBalancer" }}
  {{- if .Values.plgx.fileserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.plgx.fileserver.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  {{- if (or (eq .Values.plgx.fileserver.service.type "LoadBalancer") (eq .Values.plgx.fileserver.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.plgx.fileserver.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: {{ .Values.plgx.fileserver.serviceType | default "ClusterIP" }}
  selector:
    name: {{ template "polylogyx.fullname" . }}-fileserver
{{ end }}