{{- if and .Values.plgx.persistence.carves.enabled (not .Values.plgx.persistence.carves.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "polylogyx.fullname" . }}-carves-pvc
  labels:
    name: {{ template "polylogyx.fullname" . }}-carves-pvc
spec:
  accessModes:
    - {{ .Values.plgx.persistence.carves.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.plgx.persistence.carves.size | quote }}
  {{- include "polylogyx.carves.storageClass" . | nindent 2 }}
{{- end -}}